      type: recipes
    values:
      layout: single
      author_profile: true
      share: true
  # _pets
  - scope:
      path: ""
      type: pets
    values:
      layout: single
      author_profile: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      sitemap:         true
      share: true
      comment: true
  # _redirectlink
  - scope:
      path: ""
      type: redirectlink
    values:
      layout: single
      author_profile: false
      share: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      sitemap:         true
      share: true
      comment: true
